### PR TITLE
Build on qt 6.2

### PR DESCRIPTION
**Pull request by divad4a**
Fix for following error:
```

/home/vboxuser/FEL/shvspy/3rdparty/libshv/libshvbroker/src/brokerapp.cpp:751:20: error: 'class QFuture<QFuture<QJsonDocument> >' has no member named 'unwrap'
  751 |                 }).unwrap().then(this, [this] (const QJsonDocument& json) {
```

Unwrap function is only available in QT v6.4 and after.

### CODE REVIEW

**Review by syyyr — APPROVED** [review]

**Comment by syyyr** [comment]
Thanks.
